trigger:
  - main

pool:
  personal-laptop: 'rlandesman-mbp'

variables:
  imageName: 'pipelines-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
