resources:
  - repo: self
    fetchDepth: 1
pool:
  name: personal-laptop

trigger:
  - main

variables:
  DockerImageName: 'production-390505/JokesDemo'

steps:
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gcr-registry'

- task: Docker@2
  displayName: 'Build image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    repository: '$(DockerImageName)'
    tags: '$(Build.BuildId)'
    arguments: '--platform linux/amd64'

- task: Docker@2
  displayName: 'Push image'
  inputs:
    command: push
    repository: '$(DockerImageName)'
    tags: '$(Build.BuildId)'
