resources:
  - repo: self
    fetchDepth: 1
pool:
  name: personal-laptop

trigger: none

pr:
  branches:
    include:
    - '*'

variables:
  DockerImageName: 'production-390505/JokesDemo'
steps:
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gcr-tutorial'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    # Use the dockerfile in the root directory
    Dockerfile: '**/Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'
